-- -- Here you define your own workspaces (is not included in the repo)
-- local w = require('utils.neorg-workspaces')
--
-- return {
--     "nvim-neorg/neorg",
--     --build = ":Neorg sync-parsers",
--     dependencies = { "nvim-lua/plenary.nvim", "vhyrro/luarocks.nvim", },
--     config = function()
--         require("neorg").setup {
--             load = {
--                 ["core.defaults"] = {},
--                 ["core.concealer"] = {},
--                 ["core.dirman"] = {
--                     config = {
--                         workspaces = w,
--                         default_workspace = "notes",
--                     },
--                 },
--             },
--         }
--
--         vim.wo.foldlevel = 99
--         vim.wo.conceallevel = 2
--     end,
-- }
return {}
